name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  terratest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: test/go.mod
          cache: true

      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ vars.CORE_APPLY_ROLE }}
          aws-region: us-east-1

      - run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile core-profile
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile core-profile
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile core-profile

      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ vars.SANDBOX_APPLY_ROLE }}
          aws-region: us-east-1

      - shell: bash
        working-directory: test
        env:
          TF_VAR_route53_profile: core-profile
          TF_VAR_route53_zone_id: ${{ secrets.CORE_HOSTED_ZONE_ID }}
          TF_VAR_route53_zone_name: ${{ secrets.CORE_HOSTED_ZONE_NAME }}
        run: |
          go install github.com/jstemmer/go-junit-report@latest
          go test -timeout 20m -v ./... | tee report.txt
          go-junit-report -set-exit-code < report.txt > report.xml

      - uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: test/report.xml
        if: always()
